#!/usr/bin/env python3
''' mixed list
'''
from typing import List, Union


def sum_mixed_list(mxd_lst: List[Union[int, float]]) -> float:
    '''Computes sum of list of numbers and floating-point number
    '''
    return float(sum(mxd_lst))
